% Plot pipe inner-surface point cloud generated by pipe_surface_visualizer.py.
%
% Usage in MATLAB:
%   cd('C:\Users\minam\Documents\Codex\2026-05-29\windows-pc-keyence-lk-g85a-lk\sensor_logger')
%   plot_pipe_surface_matlab
%
% Change csvFile below if you generated another point-cloud CSV.

csvFile = 'angle_step_log_5mm_point_cloud.csv';
T = readtable(csvFile);

figure('Name', 'Pipe Surface Point Cloud');
scatter3(T.x_mm, T.y_mm, T.z_mm, 28, T.depth_mm, 'filled');
axis equal;
grid on;
xlabel('pipe axis x [mm]');
ylabel('y [mm]');
zlabel('z [mm]');
title('Pipe inner-surface point cloud');
cb = colorbar;
cb.Label.String = 'depth [mm]';
view(35, 25);

figure('Name', 'Unwrapped Pipe Map');
scatter(T.axis_mm, T.angle_deg, 36, T.depth_mm, 'filled');
grid on;
xlabel('pipe axis [mm]');
ylabel('servo angle [deg]');
title('Unwrapped pipe map');
cb = colorbar;
cb.Label.String = 'depth [mm]';
