[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

[env:esp32dev_usb_debug]
extends = env:esp32dev
upload_speed = 115200
build_flags =
  -DUSB_TELEMETRY=1

[env:esp32dev_ota_ap]
extends = env:esp32dev
upload_protocol = espota
upload_port = 192.168.4.1
upload_flags =
  --auth=esconota

[env:esp32dev_ota_wifi]
extends = env:esp32dev
upload_protocol = espota
upload_port = esp32-escon.local
upload_flags =
  --auth=esconota
